environment: dev
http:
  port: "8080"

mysql:
  dsn: "root:Aa13892349048!@tcp(127.0.0.1:3306)/taskdb?charset=utf8mb4&parseTime=true&loc=Local"
  max_open_conns: 50
  max_idle_conns: 25
  conn_max_lifetime: "30m"

jwt:
  secret: "dev-secret"
  access_token_ttl: "1h"

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0

cache:
  ttl: "300s"
  null_ttl: "30s"
  local_cap: 1000
  jitter_sec: 60